name: Actions Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:
  
  schedule:
    - cron:  "*/60 * * * *"

jobs:
  actions_test_1:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - run: echo actions_test_1
      
  actions_test_2:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - run: echo actions_test_2
  
  actions_test_3:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - run: echo actions_test_3
      
  actions_test_4:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - run: echo actions_test_4
      
  actions_test_5:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - run: echo actions_test_5
